name: ar_flutter_plugin_plus_example
description: Demonstrates how to use the ar_flutter_plugin_plus plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  ar_flutter_plugin_plus:
    # When depending on this package from a real application you should use:
    #   ar_flutter_plugin_plus: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  cupertino_icons: ^1.0.2

  # Firebase dependencies to shared and manage cloud anchor IDs and related content
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  geoflutterfire_plus: ^0.0.33
  path_provider: ^2.1.5
  flutter_archive: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - Images/
    - Models/
    - Models/Chicken_01/
